[package]
name = "compiler-design"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "170"
lazy_static = "1.4"
once_cell = "1.7"
